liquor_sales:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: mydsaiproject0001
      dataset: liquor_demo
      threads: 4
      keyfile: /home/kennywong/code/ntu-sctp/repos/5m-data-2.6-data-pipelines-orchestration/bigquery-admin-key.json
      location: US
